// Curated emoji catalog for the picker and the ":" shortcut, grouped like
// Confluence's browser. Names are the search/shortcut keys (:thumbsup:).
export interface EmojiEntry {
  ch: string
  name: string
}

export const EMOJI_GROUPS: { group: string; items: EmojiEntry[] }[] = [
  {
    group: 'People',
    items: [
      { ch: '😀', name: 'grinning' }, { ch: '😃', name: 'smiley' }, { ch: '😄', name: 'smile' },
      { ch: '😁', name: 'grin' }, { ch: '😆', name: 'laughing' }, { ch: '😅', name: 'sweat_smile' },
      { ch: '🤣', name: 'rofl' }, { ch: '😂', name: 'joy' }, { ch: '🙂', name: 'slight_smile' },
      { ch: '😉', name: 'wink' }, { ch: '😊', name: 'blush' }, { ch: '😇', name: 'innocent' },
      { ch: '🥰', name: 'smiling_face_with_hearts' }, { ch: '😍', name: 'heart_eyes' },
      { ch: '🤩', name: 'star_struck' }, { ch: '😘', name: 'kissing_heart' },
      { ch: '😋', name: 'yum' }, { ch: '😜', name: 'stuck_out_tongue_winking_eye' },
      { ch: '🤔', name: 'thinking' }, { ch: '🤨', name: 'raised_eyebrow' },
      { ch: '😐', name: 'neutral_face' }, { ch: '😏', name: 'smirk' }, { ch: '🙄', name: 'eye_roll' },
      { ch: '😴', name: 'sleeping' }, { ch: '🤒', name: 'sick' }, { ch: '🥳', name: 'partying_face' },
      { ch: '😎', name: 'sunglasses' }, { ch: '🤓', name: 'nerd' }, { ch: '😕', name: 'confused' },
      { ch: '😢', name: 'cry' }, { ch: '😭', name: 'sob' }, { ch: '😤', name: 'triumph' },
      { ch: '😠', name: 'angry' }, { ch: '🤯', name: 'exploding_head' }, { ch: '😱', name: 'scream' },
      { ch: '🥺', name: 'pleading_face' }, { ch: '😮', name: 'open_mouth' }, { ch: '🤗', name: 'hugging' },
      { ch: '🤫', name: 'shushing_face' }, { ch: '🤝', name: 'handshake' }, { ch: '👋', name: 'wave' },
      { ch: '👍', name: 'thumbsup' }, { ch: '👎', name: 'thumbsdown' }, { ch: '👏', name: 'clap' },
      { ch: '🙌', name: 'raised_hands' }, { ch: '🙏', name: 'pray' }, { ch: '💪', name: 'muscle' },
      { ch: '✌️', name: 'victory' }, { ch: '🤞', name: 'crossed_fingers' }, { ch: '👉', name: 'point_right' },
      { ch: '👀', name: 'eyes' }, { ch: '🧠', name: 'brain' }, { ch: '🗣️', name: 'speaking_head' },
    ],
  },
  {
    group: 'Nature',
    items: [
      { ch: '🐶', name: 'dog' }, { ch: '🐱', name: 'cat' }, { ch: '🐭', name: 'mouse' },
      { ch: '🦊', name: 'fox' }, { ch: '🐻', name: 'bear' }, { ch: '🐼', name: 'panda' },
      { ch: '🦁', name: 'lion' }, { ch: '🐸', name: 'frog' }, { ch: '🐢', name: 'turtle' },
      { ch: '🦋', name: 'butterfly' }, { ch: '🐝', name: 'bee' }, { ch: '🐞', name: 'ladybug' },
      { ch: '🌱', name: 'seedling' }, { ch: '🌲', name: 'evergreen_tree' }, { ch: '🌴', name: 'palm_tree' },
      { ch: '🌵', name: 'cactus' }, { ch: '🌸', name: 'cherry_blossom' }, { ch: '🌹', name: 'rose' },
      { ch: '🌻', name: 'sunflower' }, { ch: '🍀', name: 'four_leaf_clover' }, { ch: '🍁', name: 'maple_leaf' },
      { ch: '🌍', name: 'earth_africa' }, { ch: '🌞', name: 'sun_with_face' }, { ch: '🌙', name: 'crescent_moon' },
      { ch: '⭐', name: 'star' }, { ch: '🌟', name: 'star2' }, { ch: '⚡', name: 'zap' },
      { ch: '🔥', name: 'fire' }, { ch: '🌈', name: 'rainbow' }, { ch: '☀️', name: 'sunny' },
      { ch: '☁️', name: 'cloud' }, { ch: '🌧️', name: 'rain_cloud' }, { ch: '❄️', name: 'snowflake' },
      { ch: '🌬️', name: 'wind_face' }, { ch: '🌊', name: 'ocean' }, { ch: '💧', name: 'droplet' },
    ],
  },
  {
    group: 'Food',
    items: [
      { ch: '🍏', name: 'green_apple' }, { ch: '🍎', name: 'apple' }, { ch: '🍊', name: 'tangerine' },
      { ch: '🍋', name: 'lemon' }, { ch: '🍌', name: 'banana' }, { ch: '🍉', name: 'watermelon' },
      { ch: '🍇', name: 'grapes' }, { ch: '🍓', name: 'strawberry' }, { ch: '🥝', name: 'kiwi' },
      { ch: '🍅', name: 'tomato' }, { ch: '🥑', name: 'avocado' }, { ch: '🌽', name: 'corn' },
      { ch: '🥕', name: 'carrot' }, { ch: '🍞', name: 'bread' }, { ch: '🧀', name: 'cheese' },
      { ch: '🍕', name: 'pizza' }, { ch: '🍔', name: 'hamburger' }, { ch: '🌮', name: 'taco' },
      { ch: '🍣', name: 'sushi' }, { ch: '🍜', name: 'ramen' }, { ch: '🍩', name: 'doughnut' },
      { ch: '🍪', name: 'cookie' }, { ch: '🎂', name: 'birthday' }, { ch: '🍰', name: 'cake' },
      { ch: '🍫', name: 'chocolate_bar' }, { ch: '🍿', name: 'popcorn' }, { ch: '☕', name: 'coffee' },
      { ch: '🍵', name: 'tea' }, { ch: '🥤', name: 'cup_with_straw' }, { ch: '🧊', name: 'ice' },
    ],
  },
  {
    group: 'Activity',
    items: [
      { ch: '⚽', name: 'soccer' }, { ch: '🏀', name: 'basketball' }, { ch: '🏈', name: 'football' },
      { ch: '⚾', name: 'baseball' }, { ch: '🎾', name: 'tennis' }, { ch: '🏐', name: 'volleyball' },
      { ch: '🎱', name: 'eight_ball' }, { ch: '🏓', name: 'ping_pong' }, { ch: '🏸', name: 'badminton' },
      { ch: '🥅', name: 'goal' }, { ch: '⛳', name: 'golf' }, { ch: '🏹', name: 'archery' },
      { ch: '🎣', name: 'fishing' }, { ch: '🥊', name: 'boxing_glove' }, { ch: '🎽', name: 'running_shirt' },
      { ch: '🛹', name: 'skateboard' }, { ch: '⛷️', name: 'skier' }, { ch: '🏂', name: 'snowboarder' },
      { ch: '🏋️', name: 'weight_lifter' }, { ch: '🚴', name: 'bicyclist' }, { ch: '🏆', name: 'trophy' },
      { ch: '🥇', name: 'first_place' }, { ch: '🥈', name: 'second_place' }, { ch: '🥉', name: 'third_place' },
      { ch: '🏅', name: 'medal' }, { ch: '🎯', name: 'dart' }, { ch: '🎮', name: 'video_game' },
      { ch: '🎲', name: 'game_die' }, { ch: '🧩', name: 'puzzle_piece' }, { ch: '🎳', name: 'bowling' },
      { ch: '🎤', name: 'microphone' }, { ch: '🎧', name: 'headphones' }, { ch: '🎸', name: 'guitar' },
      { ch: '🎹', name: 'musical_keyboard' }, { ch: '🥁', name: 'drum' }, { ch: '🎬', name: 'clapper' },
      { ch: '🎨', name: 'art' }, { ch: '🎭', name: 'performing_arts' }, { ch: '🎪', name: 'circus_tent' },
    ],
  },
  {
    group: 'Travel',
    items: [
      { ch: '🚗', name: 'car' }, { ch: '🚕', name: 'taxi' }, { ch: '🚌', name: 'bus' },
      { ch: '🚑', name: 'ambulance' }, { ch: '🚒', name: 'fire_engine' }, { ch: '🚚', name: 'truck' },
      { ch: '🚜', name: 'tractor' }, { ch: '🏍️', name: 'motorcycle' }, { ch: '🚲', name: 'bike' },
      { ch: '🚂', name: 'steam_locomotive' }, { ch: '🚆', name: 'train' }, { ch: '🚇', name: 'metro' },
      { ch: '✈️', name: 'airplane' }, { ch: '🚀', name: 'rocket' }, { ch: '🛸', name: 'flying_saucer' },
      { ch: '🚁', name: 'helicopter' }, { ch: '⛵', name: 'sailboat' }, { ch: '🚢', name: 'ship' },
      { ch: '⚓', name: 'anchor' }, { ch: '🗺️', name: 'world_map' }, { ch: '🧭', name: 'compass' },
      { ch: '🏔️', name: 'mountain' }, { ch: '🏕️', name: 'camping' }, { ch: '🏖️', name: 'beach' },
      { ch: '🏙️', name: 'cityscape' }, { ch: '🏠', name: 'house' }, { ch: '🏢', name: 'office' },
      { ch: '🏥', name: 'hospital' }, { ch: '🏦', name: 'bank' }, { ch: '🏗️', name: 'construction' },
      { ch: '🗽', name: 'statue_of_liberty' }, { ch: '🕌', name: 'mosque' }, { ch: '⛩️', name: 'shinto_shrine' },
    ],
  },
  {
    group: 'Objects',
    items: [
      { ch: '💻', name: 'computer' }, { ch: '🖥️', name: 'desktop' }, { ch: '⌨️', name: 'keyboard' },
      { ch: '🖱️', name: 'mouse_device' }, { ch: '📱', name: 'iphone' }, { ch: '☎️', name: 'phone' },
      { ch: '🔋', name: 'battery' }, { ch: '🔌', name: 'electric_plug' }, { ch: '💡', name: 'bulb' },
      { ch: '🔦', name: 'flashlight' }, { ch: '🕯️', name: 'candle' }, { ch: '🗑️', name: 'wastebasket' },
      { ch: '💰', name: 'moneybag' }, { ch: '💳', name: 'credit_card' }, { ch: '💎', name: 'gem' },
      { ch: '⚖️', name: 'scales' }, { ch: '🔧', name: 'wrench' }, { ch: '🔨', name: 'hammer' },
      { ch: '⚙️', name: 'gear' }, { ch: '🧲', name: 'magnet' }, { ch: '🔬', name: 'microscope' },
      { ch: '🔭', name: 'telescope' }, { ch: '💊', name: 'pill' }, { ch: '🩺', name: 'stethoscope' },
      { ch: '🚪', name: 'door' }, { ch: '🛒', name: 'shopping_cart' }, { ch: '🎁', name: 'gift' },
      { ch: '🎈', name: 'balloon' }, { ch: '🎉', name: 'tada' }, { ch: '🎊', name: 'confetti_ball' },
      { ch: '✉️', name: 'envelope' }, { ch: '📦', name: 'package' }, { ch: '📅', name: 'calendar' },
      { ch: '📋', name: 'clipboard' }, { ch: '📌', name: 'pushpin' }, { ch: '📎', name: 'paperclip' },
      { ch: '✂️', name: 'scissors' }, { ch: '📏', name: 'ruler' }, { ch: '🔒', name: 'lock' },
      { ch: '🔑', name: 'key' }, { ch: '📚', name: 'books' }, { ch: '📖', name: 'book' },
      { ch: '📝', name: 'memo' }, { ch: '✏️', name: 'pencil' }, { ch: '🖊️', name: 'pen' },
      { ch: '📊', name: 'bar_chart' }, { ch: '📈', name: 'chart_increasing' }, { ch: '📉', name: 'chart_decreasing' },
      { ch: '🗂️', name: 'card_index_dividers' }, { ch: '📁', name: 'file_folder' }, { ch: '🗄️', name: 'file_cabinet' },
      { ch: '⏰', name: 'alarm_clock' }, { ch: '⏳', name: 'hourglass' }, { ch: '🧪', name: 'test_tube' },
    ],
  },
  {
    group: 'Symbols',
    items: [
      { ch: '❤️', name: 'heart' }, { ch: '🧡', name: 'orange_heart' }, { ch: '💛', name: 'yellow_heart' },
      { ch: '💚', name: 'green_heart' }, { ch: '💙', name: 'blue_heart' }, { ch: '💜', name: 'purple_heart' },
      { ch: '🖤', name: 'black_heart' }, { ch: '💔', name: 'broken_heart' }, { ch: '💯', name: '100' },
      { ch: '✅', name: 'white_check_mark' }, { ch: '☑️', name: 'ballot_box_with_check' }, { ch: '✔️', name: 'heavy_check_mark' },
      { ch: '❌', name: 'x' }, { ch: '❗', name: 'exclamation' }, { ch: '❓', name: 'question' },
      { ch: '⚠️', name: 'warning' }, { ch: '🚫', name: 'no_entry_sign' }, { ch: '♻️', name: 'recycle' },
      { ch: '🔴', name: 'red_circle' }, { ch: '🟠', name: 'orange_circle' }, { ch: '🟡', name: 'yellow_circle' },
      { ch: '🟢', name: 'green_circle' }, { ch: '🔵', name: 'blue_circle' }, { ch: '🟣', name: 'purple_circle' },
      { ch: '⭕', name: 'o' }, { ch: '🔺', name: 'small_red_triangle' }, { ch: '💬', name: 'speech_balloon' },
      { ch: '💭', name: 'thought_balloon' }, { ch: '🔔', name: 'bell' }, { ch: '🎵', name: 'musical_note' },
      { ch: '➕', name: 'heavy_plus_sign' }, { ch: '➖', name: 'heavy_minus_sign' }, { ch: '➗', name: 'heavy_division_sign' },
      { ch: '✖️', name: 'heavy_multiplication_x' }, { ch: '♾️', name: 'infinity' }, { ch: '🔗', name: 'link' },
      { ch: '🏁', name: 'checkered_flag' }, { ch: '🚩', name: 'triangular_flag' }, { ch: '🔖', name: 'bookmark' },
    ],
  },
]

export const ALL_EMOJI: EmojiEntry[] = EMOJI_GROUPS.flatMap((g) => g.items)
