apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskhat.fullname" . }}-api
  labels:
    {{- include "taskhat.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "taskhat.selectorLabels" (dict "root" . "component" "api") | nindent 4 }}
  ports:
    - name: http
      port: 8081
      targetPort: http
