apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskhat.fullname" . }}-web
  labels:
    {{- include "taskhat.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "taskhat.selectorLabels" (dict "root" . "component" "web") | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
